#!/bin/bash

if [ ! -e /opt/nvidia/bin/nvidia-container-runtime-hook ]; then
	exit 0
fi

if [ $1 == "prestart" ]; then
	LD_LIBRARY_PATH=/opt/nvidia/lib PATH=/opt/nvidia/bin /opt/nvidia/bin/nvidia-container-runtime-hook -prestart
fi

